# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3e49456821477fd02e1077c20c11c41f45f0c009ee291a75b6c2508d7c6808ed76f3a10ed16486efe7dfb9eb48d23fd93b6a547b0b436b2fa5011ddabbb938e

test:
  secret_key_base: 0fdf4ac31a65afac4176a4287e5d44553280085929fb4178d1823692fd5c354409cf555acce5fff592d3b3c7c19728045557504386887a18a3b87ae5b4a9fc58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
